version: '3.8'

services:
  mkdocs:
    image: vilerio/papillon-site:latest
    deploy:
      mode: replicated
      replicas: 2
      placement:
        constraints:
          - node.role == worker
    ports:
      - "3000:3000"